"""add mobile

Revision ID: 305b80e7f921
Revises: e42bdb7b68ac
Create Date: 2025-03-01 16:57:41.295631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305b80e7f921'
down_revision: Union[str, None] = 'e42bdb7b68ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('mobile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'mobile')
    # ### end Alembic commands ###
